default: &default
  adapter: postgresql
  encoding: utf8
  user: hasan
  password: hasan
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: transport_system_development

test:
  <<: *default
  database: transport_system_test

production:
  <<: *default
  database: transport_system_production

secondbase:

  development:
    <<: *default
    database: transport_system_archive_development

  test:
    <<: *default
    database: transport_system_archive_test

  production:
    <<: *default
    database: transport_system_archive_production

